front_cloud_to_scan:
  ros__parameters:
    frame_id: front_camera_link
    pointcloud_topic: /agro_bot/front_camera/points
    scan_topic: /agro_bot/front_camera/scan
    frequency: 30
    x_max: 10.
    x_min: 0.6
    y_max: 20.0
    y_min: -20.0
    z_max: 0.2
    z_min: 0.0
    angle_max: 0.33
    angle_min: -0.33
    rays_number: 120

back_cloud_to_scan:
  ros__parameters:
    frame_id: back_camera_link
    pointcloud_topic: /agro_bot/back_camera/points
    scan_topic: /agro_bot/back_camera/scan
    frequency: 30
    x_max: 10.
    x_min: 0.6
    y_max: 20.0
    y_min: -20.0
    z_max: 0.25
    z_min: 0.0
    angle_max: 0.33
    angle_min: -0.33
    rays_number: 120

front_image_to_detection:
  ros__parameters:
    use_sim_time: False
    image_topic: /agro_bot/front_camera/image/color
    depth_topic: /agro_bot/front_camera/image/depth
    detection_topic: /agro_bot/front_camera/detection
    frequency: 30

back_image_to_detection:
  ros__parameters:
    use_sim_time: False
    image_topic: /agro_bot/back_camera/image/color
    depth_topic: /agro_bot/back_camera/image/depth
    detection_topic: /agro_bot/back_camera/detection
    frequency: 30

local_mapping:
  ros__parameters:
    frequency: 30
    front_detection_topic: /agro_bot/front_camera/detection
    back_detection_topic: /agro_bot/back_camera/detection
    front_depth_topic: /agro_bot/front_camera/image/depth
    back_depth_topic: /agro_bot/back_camera/image/depth
    front_scan_topic: /agro_bot/front_camera/scan
    back_scan_topic: /agro_bot/back_camera/scan
    odom_topic: /agro_bot/odom
    grid_topic: /agro_bot/local_map
    grid_frame: odom
    robot_frame: base_footprint
    front_camera_frame: front_camera_link
    back_camera_frame: back_camera_link
    grid_size: 30
    grid_resolution: 0.1